/*
 *       ____________
 *      /\  ________ \       
 *     /  \ \______/\ \
 *    / /\ \ \  / /\ \ \     
 *   / / /\ \ \/ / /\ \ \
 *  / / /__\ \ \/_/__\_\ \
 * / /_/____\ \___________\
 * \ \ \____/ / ________/ /
 *  \ \ \  / / /\ \  / / / 
 *   \ \ \/ / /\ \ \/ / / 
 *    \ \/ / /__\_\/ / /
 *     \  / /______\/ /
 *      \/___________/       
 *
 * Description : Random Variable Class
 * Date        : 2014 - July - 24
 * Author      : Arturo Alatriste Trujillo.
 ****************************************************************************/


package w1_factors;

import com.sun.glass.events.KeyEvent;
import java.util.ArrayList;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Arturo.Alatriste
 */
public class JFrame_RndVars extends javax.swing.JFrame {

    //public ArrayList<RandomVar> vars ;
    public RandomVarCollection vars;
    private boolean addVar = false;
    
    /**
     * Creates new form JFrame_RndVars
     */
    public JFrame_RndVars(RandomVarCollection vars ) {
        initComponents();
        
        this.vars = vars;
        iniVars();
        showVars();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jSplitPane_Vars = new javax.swing.JSplitPane();
        panelVars = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableVars = new javax.swing.JTable();
        panelPosibleValues = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableVarValues = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jToolBar1 = new javax.swing.JToolBar();
        btnAdd = new javax.swing.JButton();
        btnDetails = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jSplitPane_Vars.setDividerLocation(200);
        jSplitPane_Vars.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        panelVars.setBorder(javax.swing.BorderFactory.createTitledBorder("Variables"));
        panelVars.setName(""); // NOI18N

        tableVars.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "id", "name", "description", "cardinality"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableVars.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableVarsMouseClicked(evt);
            }
        });
        tableVars.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tableVarsKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tableVars);

        javax.swing.GroupLayout panelVarsLayout = new javax.swing.GroupLayout(panelVars);
        panelVars.setLayout(panelVarsLayout);
        panelVarsLayout.setHorizontalGroup(
            panelVarsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVarsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        panelVarsLayout.setVerticalGroup(
            panelVarsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVarsLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                .addContainerGap())
        );

        jSplitPane_Vars.setTopComponent(panelVars);

        panelPosibleValues.setBorder(javax.swing.BorderFactory.createTitledBorder("Posible Values"));

        tableVarValues.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "id", "value"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableVarValues.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tableVarValuesKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tableVarValues);

        javax.swing.GroupLayout panelPosibleValuesLayout = new javax.swing.GroupLayout(panelPosibleValues);
        panelPosibleValues.setLayout(panelPosibleValuesLayout);
        panelPosibleValuesLayout.setHorizontalGroup(
            panelPosibleValuesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPosibleValuesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        panelPosibleValuesLayout.setVerticalGroup(
            panelPosibleValuesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPosibleValuesLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                .addContainerGap())
        );

        jSplitPane_Vars.setRightComponent(panelPosibleValues);

        jTabbedPane1.addTab("Nodes ( Random variables )", jSplitPane_Vars);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 729, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Edges", jPanel1);

        jToolBar1.setRollover(true);

        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/w1_factors/icons/Sign-Add-icon.png"))); // NOI18N
        btnAdd.setToolTipText("Add new Random Variable");
        btnAdd.setFocusable(false);
        btnAdd.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAdd.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jToolBar1.add(btnAdd);

        btnDetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/w1_factors/icons/Filetype-Document-icon.png"))); // NOI18N
        btnDetails.setToolTipText("add values");
        btnDetails.setFocusable(false);
        btnDetails.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDetails.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetailsActionPerformed(evt);
            }
        });
        jToolBar1.add(btnDetails);

        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/w1_factors/icons/Log-Out-icon.png"))); // NOI18N
        btnExit.setToolTipText("Close");
        btnExit.setFocusable(false);
        btnExit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jToolBar1.add(btnExit);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableVarsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableVarsMouseClicked
        
        deleteRows(tableVarValues);
        int row = tableVars.getSelectedRow();
        int id = (int) tableVars.getValueAt(row, 0) ;
       
        for(int i=0; i < vars.size() ; i++)
        {
            if (id == vars.get(i).getId() )
            {
                showVarValues( vars.get(i).getValues());
                break;
            }
        }
    }//GEN-LAST:event_tableVarsMouseClicked

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetailsActionPerformed
        JTablex.addRow(tableVarValues);
        
    }//GEN-LAST:event_btnDetailsActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        
        JTablex.addRow(tableVars);
        addVar = true;
    }//GEN-LAST:event_btnAddActionPerformed

    private ArrayList<String> GetVarValues()
    {
        ArrayList<String> a = new ArrayList<String>();
        
        for(int r = 0; r < tableVarValues.getRowCount(); r++ )
        {
            a.add( tableVarValues.getValueAt(r, 1).toString() ) ;
        }    
        return a;
    }
    
    private void tableVarValuesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tableVarValuesKeyReleased
        
        if ( evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            System.out.println( "keycode: KeyEvent.VK_ENTER" );

            //master
            int r = tableVars.getSelectedRow();
            int id = (int) tableVars.getValueAt( r, 0);
            RandomVar v = vars.getById(id);
            
            //detail
            //int rDtl = tableVarValues.getSelectedRow();
            //v.getValues().add( tableVarValues.getValueAt( rDtl, 1).toString() );
            ArrayList a = GetVarValues();
            v.setValues( GetVarValues() );

        }
                

        
        
    }//GEN-LAST:event_tableVarValuesKeyReleased

    private void tableVarsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tableVarsKeyReleased
        
        if ( evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            if ( addVar )
            {
                int    r    =          tableVars.getSelectedRow();
                int    id   = (int)    tableVars.getValueAt( r, 0);
                String name = (String) tableVars.getValueAt( r, 1);
                String desc = (String) tableVars.getValueAt( r, 2);
                
                RandomVar v = new RandomVar( id, name, desc );
                vars.add(v);
                addVar = false;
            }
        }
    }//GEN-LAST:event_tableVarsKeyReleased

    /**
     * Create and Initialize the lists of Random variables.
     */
    public void iniVars(){
        vars.clear();
        
        RandomVar v1 = new RandomVar(1, "v1", "Difficulty"  , new String[] { "easy", "hard"              });
        RandomVar v2 = new RandomVar(2, "v2", "Intelligence", new String[] { "low", "brilliant"          });
        RandomVar v3 = new RandomVar(3, "v3", "Grade"       , new String[] { "A", "B", "C"               });
        RandomVar v4 = new RandomVar(4, "v4", "Sat"         , new String[] { "excellent", "good", "bad"  });
        RandomVar v5 = new RandomVar(5, "v5", "Letter"      , new String[] { "recommendation", "ignored" });
        vars.add( v1 );
        vars.add( v2 );
        vars.add( v3 );
        vars.add( v4 );
        vars.add( v5 );
    }
    
    public void showVars(){
        
        //tableVars.getce
        for(int r = 0; r < vars.size(); r++ )
        {
            System.out.println( vars.get(r).getName());
            
            tableVars.setValueAt(vars.get(r).getId(),          r, 0);
            tableVars.setValueAt(vars.get(r).getName(),        r, 1);
            tableVars.setValueAt(vars.get(r).getDescription(), r, 2);
            tableVars.setValueAt(vars.get(r).getCardinality(), r, 3);
        }
    }
            
    protected void showVarValues(ArrayList<String> values){ 

        deleteRows(tableVarValues);
        
        for(int i=0; i < values.size(); i++)
        {
            varValueInsertRow( Integer.toString(i), values.get(i) );
        }
    }


    protected void deleteRows(JTable table){
        DefaultTableModel dm = (DefaultTableModel) table.getModel();
        int rowCount=dm.getRowCount();
        for (int i = 0; i < rowCount; i++) {
            dm.removeRow(0);
        }    
    }

    protected void varValueInsertRow(String id, String value ){
        DefaultTableModel dm = (DefaultTableModel) tableVarValues.getModel();
        dm.addRow(new Object[] { id, value} );
    }
            
    
    /*
     * @param args the command line arguments
     
    public static void main(String args[]) {
        // Set the Nimbus look and feel 
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        // If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        //  For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
        / /
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame_RndVars.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame_RndVars.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame_RndVars.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_RndVars.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        // Create and display the form 
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame_RndVars().setVisible(true);
            }
        });
    }
    */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDetails;
    private javax.swing.JButton btnExit;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSplitPane jSplitPane_Vars;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JPanel panelPosibleValues;
    private javax.swing.JPanel panelVars;
    private javax.swing.JTable tableVarValues;
    private javax.swing.JTable tableVars;
    // End of variables declaration//GEN-END:variables
}
